<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Guest;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $employees = [
            [
                "nip" => "199610102019022001",
                "name" => "Ida Faridatul Alawiyah, S.ST",
                'position' => 'Penyuluh Pertanian Pertama',
                'sex' => 0,
                'phone_number' => '0864003134',
                'academic_background' => 'Sarjana',
                'start_date' => '2020-03-11',
                'birth' => '1996-10-10',
                'address' => 'Psr. Agus Salim No. 620',
                'file_image' => 'employee-image/ida.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                "employee_status" => "INTERNAL",
                "user_status" => "ADMIN",
            ],
            [
                "nip" => "198609262015051002",
                "name" => "Awanis, S.TP., M.Si",
                'position' => 'Penyuluh Pertanian Pertama',
                'position' => 'Peneliti Pertama',
                'sex' => 0,
                'phone_number' => '08132380561',
                'academic_background' => 'Sarjana',
                'start_date' => '2015-11-21',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/awanis.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                "employee_status" => "INTERNAL",
                "user_status" => "RECEPTIONIST",
            ],
            [
                "nip" => "198609262015051007",
                "name" => "Muhammad Ali",
                'position' => 'Penyuluh Pertanian Pertama',
                'sex' => 1,
                'phone_number' => '08797019014',
                'academic_background' => 'Sarjana',
                'start_date' => '2020-03-11',
                'birth' => '1986-09-26',
                'address' => 'Dk. Babadak No. 557',
                'file_image' => 'employee-image/m ali.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                "employee_status" => "EXTERNAL",
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262015051003",
                "name" => "Muhammad Syarif, S.ST",
                'position' => 'Penyuluh Pertanian Pertama',
                'sex' => 1,
                'phone_number' => '0880944746',
                'academic_background' => 'Sarjana',
                'start_date' => '2020-03-11',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/m syarif.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                "employee_status" => "INTERNAL",
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262015051331",
                "name" => "Puspita Harum Maharani, M.Sc",
                'position' => 'Peneliti Pertama',
                'sex' => 0,
                'phone_number' => '08379476457',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/puspita.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051331",
                "name" => "Ahmad Isa Anshari, SE",
                'position' => 'Penata Muda',
                'sex' => 1,
                'phone_number' => '086007427972',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/isa.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051332",
                "name" => "Ade Hasan Basri",
                'position' => 'Fungsional Urusan Kepegawaian',
                'sex' => 1,
                'phone_number' => '0885293739',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/ade hasan b.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051333",
                "name" => "Akli",
                'position' => 'Petugas Keamanan',
                'sex' => 1,
                'phone_number' => '08864354298',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/akli.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051334",
                "name" => "Alfianoor",
                'position' => 'Teknisi',
                'sex' => 1,
                'phone_number' => '083565749271',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/alfi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051335",
                "name" => "Ariadi, S.Pi",
                'position' => 'Peneliti',
                'sex' => 1,
                'phone_number' => '083332956901',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/ariadi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051336",
                "name" => "Bachtiar",
                'position' => 'Pengemudi',
                'sex' => 1,
                'phone_number' => '08605803450',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/bachtiar.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051337",
                "name" => "Jumarni",
                'position' => 'Teknisi',
                'sex' => 0,
                'phone_number' => '0822572958',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/bu jumarni.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051338",
                "name" => "Kusyanti",
                'position' => 'Fungsional Umum',
                'sex' => 0,
                'phone_number' => '08205720809',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/bu kusyanti.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051339",
                "name" => "Gusti Maisarah",
                'position' => 'Fungsional Umum',
                'sex' => 0,
                'phone_number' => '0894410658393',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/bu sarah.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051340",
                "name" => "Agus Setiati",
                'position' => 'Penata Muda',
                'sex' => 0,
                'phone_number' => '08581746425',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/bu tia.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051341",
                "name" => "Fiqy Hilmawan, S.Pt., M.Si",
                'position' => 'Penata Muda',
                'sex' => 1,
                'phone_number' => '089556748780',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/fiqy.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198619262115051341",
                "name" => "Firmansyah, S.AP",
                'position' => 'Fungsional Arsiparis',
                'sex' => 1,
                'phone_number' => '0861771854',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/firmansyah.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051342",
                "name" => "Juhdy",
                'position' => 'Pengemudi',
                'sex' => 1,
                'phone_number' => '083922103384',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/juhdi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051344",
                "name" => "Kamaruddin",
                'position' => 'Pengemudi',
                'sex' => 1,
                'phone_number' => '08329884266',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/kamaruddin.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051346",
                "name" => "Masdar",
                'position' => 'Teknisi',
                'sex' => 1,
                'phone_number' => '0835011546',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/m yusuf brb.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051347",
                "name" => "Pagiyanto, S.ST",
                'position' => 'Penata Muda',
                'sex' => 1,
                'phone_number' => '08815604621',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/pa pagi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051348",
                "name" => "Sumari",
                'position' => 'Pengatur Tk. I',
                'sex' => 1,
                'phone_number' => '08788660444',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/pa sumari.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051349",
                "name" => "Suradi",
                'position' => 'Petugas Keamanan',
                'sex' => 1,
                'phone_number' => '08381507587',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/pa suradi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051350",
                "name" => "Puspita Harum Maharani, SP., M.Sc",
                'position' => 'Penata Muda',
                'sex' => 0,
                'phone_number' => '0851228536',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/puspita.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051351",
                "name" => "Rasunawaty",
                'position' => 'Fungsional Umum',
                'sex' => 0,
                'phone_number' => '081009710085',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/rasunawaty.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051352",
                "name" => "Rudy Ariani",
                'position' => 'Fungsional Umum',
                'sex' => 1,
                'phone_number' => '086382126113',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/rudy ariani.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051353",
                "name" => "Shinta Anggreany, M.Si",
                'position' => 'Fungsional Umum',
                'sex' => 0,
                'phone_number' => '0889526850574',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/shinta.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051354",
                "name" => "Sudiyono",
                'position' => 'Teknisi',
                'sex' => 1,
                'phone_number' => '0822372222160',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/sudiono.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051355",
                "name" => "Sumadi",
                'position' => 'Teknisi',
                'sex' => 1,
                'phone_number' => '0884934498',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/sumadi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
            [
                "nip" => "198609262115051356",
                "name" => "Fungsional Umum",
                'position' => 'Teknisi',
                'sex' => 1,
                'phone_number' => '0873578349',
                'academic_background' => 'Sarjana',
                'start_date' => '2005-05-03',
                'birth' => '1995-01-01',
                'address' => '',
                'file_image' => 'employee-image/syamsidi.jpg',
                'file_ijazah' => '',
                'file_sk_pengangkatan' => '',
                'file_ktp' => '',
                'employee_status' => 'INTERNAL',
                "user_status" => "EMPLOYEE",
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create([
                'user_id' => User::create([
                    'name' => $employee['name'],
                    'username' => $employee['nip'],
                    'password' => bcrypt($employee['nip']),
                    'status' => $employee['user_status']
                ])->id,
                'nip' => $employee['nip'],
                'name' => $employee['name'],
                'position' => $employee['position'],
                'sex' => $employee['sex'],
                'phone_number' => $employee['phone_number'],
                'academic_background' => $employee['academic_background'],
                'start_date' => $employee['start_date'],
                'birth' => $employee['birth'],
                'address' => $employee['address'],
                'file_image' => $employee['file_image'],
                'file_ijazah' => $employee['file_ijazah'],
                'file_sk_pengangkatan' => $employee['file_sk_pengangkatan'],
                'file_ktp' => $employee['file_ktp'],
                'status' => $employee['employee_status']
            ]);
        }


        // Guests
        Guest::create([
            "employee_id" => 4,
            "user_id" => 4,
            "nik" => '3525015201880002',
            "name" => 'Nursahid Arya Suyudi',
            "phone_number" => '087821235511',
            "sex" => 1,
            "agency" => 'UNISKA',
            "necessity" => 'Magang',
            "image" => '',
        ]);

        // Research
        // $proposal_id = Proposal::create([
        //     "employee_id" => 5,
        //     "file" => "",
        //     "submitted_date" => Carbon::now(),
        //     "status" => "APPROVED",
        // ])->id;
        // $report_id = Report::create([
        //     "employee_id" => 5,
        //     "file" => "",
        //     "submitted_date" => Carbon::now(),
        //     "approved_date" => Carbon::now(),
        //     "status" => "APPROVED",
        // ])->id;
        // $research_id = Research::create([
        //     "proposal_id" => $proposal_id,
        //     "report_id" => $report_id,
        //     "title" => "APLIKASI BUKU TAMU",
        // ])->id;
        // ResearchMember::create([
        //     "employee_id" => 1,
        //     "research_id" => $research_id,
        //     "status" => "HEAD"
        // ]);
        // ResearchMember::create([
        //     "employee_id" => 2,
        //     "research_id" => $research_id,
        //     "status" => "RESEARCHER"
        // ]);
    }
}
